-- Create connection_activity table for Analytics
CREATE TABLE IF NOT EXISTS public.connection_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id TEXT, -- Can be organization_connection ID or friend_request ID
    action TEXT NOT NULL, -- 'request_sent', 'request_accepted', 'request_rejected'
    actor_id UUID REFERENCES public.users(id),
    target_id UUID REFERENCES public.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    metadata JSONB DEFAULT '{}'::jsonb
);

-- Index for faster queries
CREATE INDEX IF NOT EXISTS idx_connection_activity_created_at ON public.connection_activity(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_connection_activity_actor ON public.connection_activity(actor_id);

-- Enable RLS
ALTER TABLE public.connection_activity ENABLE ROW LEVEL SECURITY;

-- Policy: Admin can view all
CREATE POLICY "Admins can view all connection activity" 
ON public.connection_activity FOR SELECT 
TO authenticated 
USING (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role IN ('admin', 'super_admin'))
);

-- Policy: Users can insert their own activity (Service Role is safer, but this allows client-side valid logging if needed)
CREATE POLICY "Users can insert activity" 
ON public.connection_activity FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = actor_id);
