-- ⚠️ DESTRUCTIVE: Drop existing table to fix schema mismatch
DROP TABLE IF EXISTS public.connection_activity CASCADE;

-- 1. Create connection_activity table with all required columns
CREATE TABLE public.connection_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id TEXT, -- Can be organization_connection ID or friend_request ID
    action TEXT NOT NULL, -- 'request_sent', 'request_accepted', 'request_rejected', 'friend_request_sent', etc.
    actor_id UUID REFERENCES public.users(id),
    target_id UUID REFERENCES public.users(id),
    sender_role TEXT, -- 'athlete', 'organization', 'coach'
    receiver_role TEXT, -- 'athlete', 'organization', 'coach'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    metadata JSONB DEFAULT '{}'::jsonb
);

-- 2. Add Indexes for Performance
CREATE INDEX idx_conn_activity_created_at ON public.connection_activity(created_at DESC);
CREATE INDEX idx_conn_activity_actor ON public.connection_activity(actor_id);
CREATE INDEX idx_conn_activity_target ON public.connection_activity(target_id);
CREATE INDEX idx_conn_activity_action ON public.connection_activity(action);

-- 3. Enable Security (RLS)
ALTER TABLE public.connection_activity ENABLE ROW LEVEL SECURITY;

-- 4. Policies (Permissions)

-- Admins can view everything
CREATE POLICY "Admins can view all connection activity" 
ON public.connection_activity FOR SELECT 
TO authenticated 
USING (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role IN ('admin', 'super_admin'))
);

-- Users can view their own activity (as actor OR target)
CREATE POLICY "Users can view their own activity" 
ON public.connection_activity FOR SELECT 
TO authenticated 
USING (
    auth.uid() = actor_id OR auth.uid() = target_id
);

-- Users/Service can insert (Logging)
CREATE POLICY "Users can insert activity" 
ON public.connection_activity FOR INSERT 
TO authenticated 
WITH CHECK (
    -- Allow users to calculate their own logs
    true
);
